### ISSUE TITLE
Upgrade to Django 1.10

### ISSUE THREAD

**Issue by funkswing** [puruckertom/ubertool_cts#10]

**Comment by popenc** [comment]
Runs fine locally with settings.py, getting error on server 1 with access CTS page:

> django:django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet

Seems like a matter of the settings_apache.py file working with the upgrade from 1.6 to 1.10. Working to resolve this soon.

**Comment by popenc** [comment]
wsgi_apache.py was:

> application = django.core.handlers.wsgi.WSGIHandler()

instead of:

> application = django.core.wsgi.get_wsgi_application()
