### ISSUE TITLE
Average column for p-chem properties 

### ISSUE THREAD

**Issue by popenc** [puruckertom/ubertool_cts#3]
The p-chem properties calculations needs an "average" column that computes, well, computes an average based on the calculators' values.

**Comment by pavgup** [comment]
It is done!  Check out pavgup/TEST-Refreshed-Async#56fc0 (can I tag a private repo?).  Check it!  Build still broken, however.

**Comment by pavgup** [comment]
Actually, I take it back, this is no longer finished.  The consensus method is essentially an average... easy to put back, but probably redundant.
